// Type definitions for the MyBodyWeight data model.
// Originally generated by @caffeineai/bindgen from the Motoko canister
// candid interface; trimmed to keep only the types/enums used by the
// frontend now that data lives in localStorage instead of an ICP canister.

export type Principal = string;

export type DeckId = bigint;
export type Timestamp = bigint;
export interface Card {
  id: CardId;
  rank: Rank;
  suit: Suit;
  exercise: string;
  deckId: DeckId;
  imageUrl: string;
  repSpec: RepSpec;
  videoUrl: string;
}
export interface DeckIdentity {
  equipment: string;
  difficulty: string;
  name: string;
  isAvailable: boolean;
  cardCount: bigint;
  gender: string;
  category: string;
  subtitle: string;
}
export interface AdminUserEntry {
  principal: Principal;
  tier: UserTier;
  email?: string;
  isIndefinite: boolean;
  tierExpiresAt?: bigint;
}
export type Result_1 =
  | {
      __kind__: "ok";
      ok: Array<AdminUserEntry>;
    }
  | {
      __kind__: "err";
      err: string;
    };
export interface Achievement {
  id: AchievementId;
  unlockedAt?: bigint;
  name: string;
  description: string;
  rarity: AchievementRarity;
}
export type RepSpec__1 =
  | {
      __kind__: "Half";
      Half: null;
    }
  | {
      __kind__: "Double";
      Double: null;
    }
  | {
      __kind__: "Fixed";
      Fixed: bigint;
    }
  | {
      __kind__: "QueenChallenge";
      QueenChallenge: string;
    }
  | {
      __kind__: "JokerCombo";
      JokerCombo: null;
    };
export interface WorkoutSessionView {
  id: SessionId;
  currentIndex: bigint;
  startTime: Timestamp;
  status: SessionStatus;
  totalCards: bigint;
  deckId: DeckId;
  cardCount: bigint;
  elapsedSeconds: bigint;
  remainingCards: bigint;
  estimatedCalories: bigint;
}
export interface Card__1 {
  id: CardId;
  imageAsset: string;
  rank: bigint;
  suit: Suit;
  exercise: string;
  deckId: DeckId;
  repSpec: RepSpec__1;
}
export type AchievementId = string;
export interface JokerCombo {
  restBetween: boolean;
  imageAsset: string;
  steps: Array<JokerComboStep>;
}
export interface Deck {
  id: DeckId;
  difficulty: DeckDifficulty;
  name: string;
  isAvailable: boolean;
  description: string;
  cardCount: bigint;
  category: DeckCategory;
}
export interface OnboardingData {
  level: string;
  gender: string;
  hasCompletedOnboarding: boolean;
}
export interface Exercise {
  difficulty: string;
  description: string;
  keyPoints: Array<string>;
  exerciseName: string;
  muscleGroups: Array<string>;
  videoUrl: string;
}
export type RepSpec =
  | {
      __kind__: "Half";
      Half: null;
    }
  | {
      __kind__: "JokerChallenge";
      JokerChallenge: null;
    }
  | {
      __kind__: "Double";
      Double: null;
    }
  | {
      __kind__: "Fixed";
      Fixed: bigint;
    };
export type SessionId = bigint;
export interface DeckWithCards {
  cards: Array<Card>;
  deck: Deck;
}
export interface SessionCard {
  challenge?: JokerChallenge;
  card: Card;
  reps: bigint;
  isMod: boolean;
}
export interface ExerciseTotal {
  totalReps: bigint;
  exerciseName: string;
}
export type Result =
  | {
      __kind__: "ok";
      ok: null;
    }
  | {
      __kind__: "err";
      err: string;
    };
export interface WorkoutSummary {
  startTime: Timestamp;
  totalCards: bigint;
  completedCards: bigint;
  durationSeconds: bigint;
  sessionId: SessionId;
  estimatedCalories: bigint;
}
export interface JokerComboStep {
  reps: bigint;
  exerciseName: string;
}
export interface WorkoutHistoryEntry {
  id: string;
  completedAt: bigint;
  aceCardsDrawn: bigint;
  userId: Principal;
  deckId: string;
  totalReps: bigint;
  kingCardsDrawn: bigint;
  durationSeconds: bigint;
  cardsCompleted: bigint;
  caloriesBurned: bigint;
  repsBySuit: {
    diamonds: bigint;
    clubs: bigint;
    spades: bigint;
    hearts: bigint;
  };
  jokerCardsDrawn: bigint;
  /** Time-validation anti-cheat (Prompt 15): sessionDuration/cardsDrawn >= 3s/card. */
  isValid: boolean;
  /** durationSeconds / cardsCompleted, in seconds. */
  avgTimePerCard: number;
  /** Reps by exercise name for this single session — see buildBreakdown()'s exerciseRows in WorkoutSummaryPage.tsx. */
  repsByExercise: Array<[string, bigint]>;
}
export interface UserProfile {
  principal: Principal;
  aceCardsDrawn: bigint;
  username: string;
  unlockedAchievements: Array<[string, bigint]>;
  createdAt: bigint;
  totalWorkouts: bigint;
  totalReps: bigint;
  email: string;
  totalCalories: bigint;
  kingCardsDrawn: bigint;
  lastWorkoutDate?: bigint;
  totalRepsPerSuit: {
    diamonds: bigint;
    clubs: bigint;
    spades: bigint;
    hearts: bigint;
  };
  longestStreak: bigint;
  fullDecksCompleted: bigint;
  currentStreak: bigint;
  jokerCardsDrawn: bigint;
  /** Lifetime reps per exercise name, accumulated across every saved WorkoutHistoryEntry. */
  repsByExercise: Array<[string, bigint]>;
  /** "Visible to nearby athletes" opt-in — always false for guest/local-only profiles, which have no concept of it. */
  discoverable: boolean;
}
export type CardId = bigint;
export enum AchievementRarity {
  Epic = "Epic",
  Rare = "Rare",
  Uncommon = "Uncommon",
  Legendary = "Legendary",
  Common = "Common",
}
export enum CardCount {
  Ten = "Ten",
  FullDeck = "FullDeck",
  Twenty = "Twenty",
}
export enum DeckCategory {
  Core = "Core",
  FullBody = "FullBody",
  UpperBody = "UpperBody",
  LowerBody = "LowerBody",
}
export enum DeckDifficulty {
  Pro = "Pro",
  Beginner = "Beginner",
  Advanced = "Advanced",
}
export enum JokerChallenge {
  DeadHang30 = "DeadHang30",
}
export enum Rank {
  Ace = "Ace",
  Six = "Six",
  Ten = "Ten",
  Two = "Two",
  Eight = "Eight",
  Seven = "Seven",
  Five = "Five",
  Four = "Four",
  Jack = "Jack",
  King = "King",
  Nine = "Nine",
  Three = "Three",
  Joker = "Joker",
  Queen = "Queen",
}
export enum SessionStatus {
  Active = "Active",
  Completed = "Completed",
}
export enum Suit {
  Diamonds = "Diamonds",
  Hearts = "Hearts",
  Clubs = "Clubs",
  Joker = "Joker",
  Spades = "Spades",
}
export enum UserTier {
  Guest = "Guest",
  Subscriber = "Subscriber",
  Registered = "Registered",
}
export interface backendInterface {
  addCard(
    deckId: DeckId,
    suit: Suit,
    rank: Rank,
    exercise: string,
    repSpec: RepSpec,
    imageUrl: string,
    videoUrl: string,
  ): Promise<CardId>;
  addDeck(
    name: string,
    description: string,
    isAvailable: boolean,
    category: DeckCategory,
    difficulty: DeckDifficulty,
  ): Promise<DeckId>;
  addExercise(exercise: Exercise): Promise<void>;
  adminGrantSubscriber(
    targetPrincipal: Principal,
    expiresAt: bigint | null,
    isIndefinite: boolean,
  ): Promise<Result>;
  adminRevokeSubscriber(targetPrincipal: Principal): Promise<Result>;
  clearLegacyCoreAdvancedFemale(): Promise<void>;
  clearLegacyCoreBeginnerFemale(): Promise<void>;
  clearLegacyCoreProFemale(): Promise<void>;
  clearLegacyFullBodyAdvancedFemale(): Promise<void>;
  clearLegacyFullBodyBeginnerFemale(): Promise<void>;
  clearLegacyFullBodyProFemale(): Promise<void>;
  clearLegacyLowerBodyAdvancedFemale(): Promise<void>;
  clearLegacyLowerBodyBeginnerFemale(): Promise<void>;
  clearLegacyLowerBodyProFemale(): Promise<void>;
  clearLegacyUpperBody(): Promise<void>;
  clearLegacyUpperBodyProFemale(): Promise<void>;
  completeWorkout(sessionId: SessionId): Promise<WorkoutSummary | null>;
  computeCoreAdvancedFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeCoreBeginnerFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeCoreProFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeFullBodyAdvancedFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeFullBodyBeginnerFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeFullBodyProFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeLowerBodyAdvancedFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeLowerBodyBeginnerFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeLowerBodyProFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeUpperBodyBeginnerTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  computeUpperBodyProFemaleTotals(
    drawnCards: Array<Card__1>,
  ): Promise<Array<ExerciseTotal>>;
  createWorkoutSession(
    deckId: DeckId,
    cardCount: CardCount,
  ): Promise<SessionId>;
  deleteDeck(id: DeckId): Promise<void>;
  getAchievements(): Promise<Array<Achievement>>;
  getAdminUserList(): Promise<Result_1>;
  getCoreAdvancedFemaleDeckIdentity(): Promise<DeckIdentity>;
  getCoreAdvancedFemaleJokerCombo(): Promise<JokerCombo>;
  getCoreBeginnerFemaleDeckIdentity(): Promise<DeckIdentity>;
  getCoreBeginnerFemaleJokerCombo(): Promise<JokerCombo>;
  getCoreProFemaleDeckIdentity(): Promise<DeckIdentity>;
  getCoreProFemaleJokerCombo(): Promise<JokerCombo>;
  getDeck(id: DeckId): Promise<DeckWithCards | null>;
  getDeckByCategory(
    category: DeckCategory,
    difficulty: DeckDifficulty,
  ): Promise<DeckWithCards | null>;
  getDecks(): Promise<Array<Deck>>;
  getExercise(exerciseName: string): Promise<Exercise | null>;
  getFullBodyAdvancedFemaleDeckIdentity(): Promise<DeckIdentity>;
  getFullBodyAdvancedFemaleJokerCombo(): Promise<JokerCombo>;
  getFullBodyBeginnerFemaleDeckIdentity(): Promise<DeckIdentity>;
  getFullBodyBeginnerFemaleJokerCombo(): Promise<JokerCombo>;
  getFullBodyProFemaleDeckIdentity(): Promise<DeckIdentity>;
  getFullBodyProFemaleJokerCombo(): Promise<JokerCombo>;
  getLowerBodyAdvancedFemaleDeckIdentity(): Promise<DeckIdentity>;
  getLowerBodyAdvancedFemaleJokerCombo(): Promise<JokerCombo>;
  getLowerBodyBeginnerFemaleDeckIdentity(): Promise<DeckIdentity>;
  getLowerBodyBeginnerFemaleJokerCombo(): Promise<JokerCombo>;
  getLowerBodyProFemaleDeckIdentity(): Promise<DeckIdentity>;
  getLowerBodyProFemaleJokerCombo(): Promise<JokerCombo>;
  getMyProfile(): Promise<
    | {
        __kind__: "ok";
        ok: UserProfile;
      }
    | {
        __kind__: "err";
        err: string;
      }
  >;
  getMyWorkoutHistory(): Promise<
    | {
        __kind__: "ok";
        ok: Array<WorkoutHistoryEntry>;
      }
    | {
        __kind__: "err";
        err: string;
      }
  >;
  getOnboarding(): Promise<OnboardingData | null>;
  getTier(userId: Principal): Promise<UserTier>;
  getUpperBodyBeginnerDeckIdentity(): Promise<DeckIdentity>;
  getUpperBodyBeginnerJokerCombo(): Promise<JokerCombo>;
  getUpperBodyProFemaleDeckIdentity(): Promise<DeckIdentity>;
  getUpperBodyProFemaleJokerCombo(): Promise<JokerCombo>;
  getUserAchievements(): Promise<Array<[string, bigint]>>;
  getWorkoutSession(sessionId: SessionId): Promise<WorkoutSessionView | null>;
  listExercises(): Promise<Array<Exercise>>;
  loginUser(
    email: string,
    passwordHash: string,
  ): Promise<
    | {
        __kind__: "ok";
        ok: UserProfile;
      }
    | {
        __kind__: "err";
        err: string;
      }
  >;
  nextCard(sessionId: SessionId): Promise<SessionCard | null>;
  registerUser(
    username: string,
    email: string,
    passwordHash: string,
  ): Promise<
    | {
        __kind__: "ok";
        ok: null;
      }
    | {
        __kind__: "err";
        err: string;
      }
  >;
  revokeTier(userId: Principal): Promise<Result>;
  saveOnboarding(gender: string, level: string): Promise<Result>;
  saveWorkoutHistory(entry: WorkoutHistoryEntry): Promise<
    | {
        __kind__: "ok";
        ok: null;
      }
    | {
        __kind__: "err";
        err: string;
      }
  >;
  seedCoreAdvancedFemaleDeck(): Promise<void>;
  seedCoreBeginnerFemaleDeck(): Promise<void>;
  seedCoreProFemaleDeck(): Promise<void>;
  seedFullBodyAdvancedFemaleDeck(): Promise<void>;
  seedFullBodyBeginnerFemaleDeck(): Promise<void>;
  seedFullBodyProFemaleDeck(): Promise<void>;
  seedLowerBodyAdvancedFemaleDeck(): Promise<void>;
  seedLowerBodyBeginnerFemaleDeck(): Promise<void>;
  seedLowerBodyProFemaleDeck(): Promise<void>;
  seedUpperBodyBeginnerDeck(): Promise<void>;
  seedUpperBodyProFemaleDeck(): Promise<void>;
  setAdminPrincipal(newAdmin: Principal): Promise<Result>;
  setTier(
    userId: Principal,
    tier: UserTier,
    expiresAt: bigint | null,
    isIndefinite: boolean,
  ): Promise<Result>;
  updateCard(
    cardId: CardId,
    exercise: string,
    repSpec: RepSpec,
    imageUrl: string,
    videoUrl: string,
  ): Promise<void>;
  updateProfile(username: string): Promise<
    | {
        __kind__: "ok";
        ok: null;
      }
    | {
        __kind__: "err";
        err: string;
      }
  >;
}
